import { type NextPage } from "next";
import Head from "next/head";
import { api } from "../utils/api";

const BuildsPage: NextPage = () => {
  const builds = api.builds.getBuilds.useQuery();
  return (
    <>
      <Head>
        <title>SC2 Builds</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen  bg-gradient-to-b from-[#2e026d] to-[#15162c]  text-white">
        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>Match Up</th>
              <th>Build</th>
            </tr>
          </thead>
          <tbody>
            {builds.data?.map((build) => (
              <tr key={build.id}>
                <td>{build.id}</td>
                <td>{build.matchUp}</td>
                <td>{build.build}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </>
  );
};

export default BuildsPage;
