import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>SC2 Builds</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen items-center justify-center bg-black">
        <Link href="/submit-build">
          <span className=" text-white">Submit New Build</span>
        </Link>
        <Link href="/submit-build">
          <span className=" text-white">View Builds</span>
        </Link>
      </div>
    </>
  );
};

export default Home;
